### ISSUE TITLE
No reply to successful `REG CREATE` with no callback

### ISSUE THREAD

**Issue by progval** [kaniini/mammon#59]
```
1 -> S: CAP LS 302
1 -> S: NICK registration_user
1 -> S: USER r e g :user
1 -> S: CAP END
S -> 1: :MyLittleServer CAP * LS * :extended-join userhost-in-names account-notify cap-notify echo-message sasl=PLAIN account-tag server-time metadata-notify
S -> 1: :MyLittleServer CAP * LS away-notify
S -> 1: :MyLittleServer NOTICE registration_user :*** Looking up your hostname...
S -> 1: :MyLittleServer NOTICE registration_user :*** Checking Ident
S -> 1: :MyLittleServer NOTICE registration_user :*** Found your hostname: localhost
S -> 1: :MyLittleServer NOTICE registration_user :*** No Ident response
S -> 1: :MyLittleServer 001 registration_user :Welcome to the MyLittleNetwork IRC Network, registration_user!~r@localhost
S -> 1: :MyLittleServer 002 registration_user :Your host is MyLittleServer, running version mammon-0
S -> 1: :MyLittleServer 003 registration_user :This server was started at Sun Dec 20 2015 at 12:48:01 CET
S -> 1: :MyLittleServer 004 registration_user MyLittleServer mammon-0 wioZ
S -> 1: :MyLittleServer 005 registration_user USERLEN= MONITOR=20 NETWORK=MyLittleNetwork CASEMAPPING=rfc3454 REGCREDTYPES=passphrase LINELEN= CHANTYPES=# TOPICLEN= REGCALLBACKS= SAFELIST NICKLEN= REGCOMMANDS=CREATE,VERIFY METADATA CHANNELLEN= :are supported by this server
S -> 1: :MyLittleServer 375 registration_user :- MyLittleServer Message of the Day -
S -> 1: :MyLittleServer 372 registration_user :- Hi
S -> 1: :MyLittleServer 376 registration_user :End of /MOTD command.
1 -> S: REG CREATE testuser * temporarypassword
```

Then the server does not reply.
Expected behavior: get [`RPL_REGISTRATION_SUCCESS`](https://github.com/ircv3/ircv3-specifications/pull/152/files#diff-68ea10e913229e36485008824d1ee525R58)

Relevant config:

```
extensions:
- mammon.ext.rfc1459.42
- mammon.ext.rfc1459.ident
- mammon.ext.ircv3.account_notify
- mammon.ext.ircv3.server_time
- mammon.ext.ircv3.echo_message
- mammon.ext.ircv3.register
- mammon.ext.ircv3.sasl
- mammon.ext.misc.nopost
register:
  enabled_callbacks:
  - none
  verify_timeout:
    days: 1
```

**Comment by Mikaela** [comment]
Shouldn't it be `REG CREATE testuser passphrase password`? That was how it told me registration successful and authentication successful on irc.dereferenced.org.

EDIT: I am not fully sure if I did it that way, but I read https://github.com/ircv3/ircv3-specifications/pull/152/files and did it the best I understood and after some attempts it told me I registered successfully.

**Comment by progval** [comment]
Doesn't change anything for me.

**Comment by DanielOaks** [comment]
I can't seem to replicate this with that config block. Mind posting a more complete config and making sure you're pulling all the returned messages?

```
22:02:49 testnet <-- REG CREATE testuser * temporarypassword
22:02:50 testnet --> :mammon.dnt 920 dan testuser :Account created
22:02:50 testnet --> :mammon.dnt 900 dan dan!~d@localhost.localdomain testuser :You are now logged in as testuser
22:02:50 testnet --> :mammon.dnt 903 dan :Authentication successful
```

**Comment by progval** [comment]
```
clients:
  # ping_frequency - client ping frequency
  ping_frequency:
    minutes: 1000

  # ping_timeout - ping timeout length
  ping_timeout:
    seconds: 10
data:
  format: json
  filename: /tmp/tmpwlgrbry5/data.json
  save_frequency:
    minutes: 5
extensions:
- mammon.ext.rfc1459.42
- mammon.ext.rfc1459.ident
- mammon.ext.ircv3.account_notify
- mammon.ext.ircv3.server_time
- mammon.ext.ircv3.echo_message
- mammon.ext.ircv3.register
- mammon.ext.ircv3.sasl
- mammon.ext.misc.nopost
metadata:
  restricted_keys: 
monitor:
  limit: 20
motd:
  - "Hi"
limits:
  foo: bar
listeners:
- {"host": "0.0.0.0", "port": 45546, "ssl": false}
logs:
  {
  }
register:
  enabled_callbacks:
  - none
  verify_timeout:
    days: 1
roles:
  "placeholder":
    title: "Just a placeholder"
server:
  name: MyLittleServer
  network: MyLittleNetwork
  recvq_len: 20
```
